server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://${CONFIG_SERVER_USERNAME:adbin}:${CONFIG_SERVER_PASSWORD:adbin}@config-server:9000}
  threads:
    virtual:
      enabled: true

security:
  public-endpoints:
    - /api/auth/**

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:1800000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}
