server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://${CONFIG_SERVER_USERNAME:adbin}:${CONFIG_SERVER_PASSWORD:adbin}@config-server:9000}
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

security:
  public-endpoints:
    - /api/auth/**

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:1800000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}

auth:
  session:
    redis:
      key-prefix:
        session: ${AUTH_SESSION_REDIS_SESSION_KEY_PREFIX:auth:session:}
        refresh: ${AUTH_SESSION_REDIS_REFRESH_KEY_PREFIX:auth:refresh:}
        user-sessions: ${AUTH_SESSION_REDIS_USER_SESSIONS_KEY_PREFIX:auth:user-sessions:}

internal-api:
  client:
    token: ${INTERNAL_API_TOKEN:internal-default-token-change-me}
