server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: health-service
              uri: lb://health
              predicates:
                - Path=/health/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG