server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://${CONFIG_SERVER_USERNAME:adbin}:${CONFIG_SERVER_PASSWORD:adbin}@config-server:9000}
  threads:
    virtual:
      enabled: true

security:
  public-endpoints:
    - /internal/users

jwt:
  secret: ${JWT_SECRET}
