server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: habit-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://${CONFIG_SERVER_USERNAME:adbin}:${CONFIG_SERVER_PASSWORD:adbin}@config-server:9000}
  threads:
    virtual:
      enabled: true

jwt:
  secret: ${JWT_SECRET}

internal-api:
  server:
    token: ${INTERNAL_API_TOKEN:internal-default-token-change-me}
  client:
    token: ${INTERNAL_API_TOKEN:internal-default-token-change-me}
