server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: eureka-server

security:
  username: ${EUREKA_SERVER_USERNAME}
  password: ${EUREKA_SERVER_PASSWORD}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true