server:
  port: ${SERVER_PORT:9000}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          username: ${CONFIG_GIT_USERNAME:}
          password: ${CONFIG_GIT_PASSWORD:}
          clone-on-start: true
          default-label: main

config-server:
  security:
    username: ${CONFIG_SERVER_USERNAME:adbin}
    password: ${CONFIG_SERVER_PASSWORD:adbin}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true